### ISSUE TITLE
How to report a bug/BUG反馈指南

### ISSUE THREAD

**Issue by Remelens** [Remelens/WD-crawler#1]
```
**describe**:
**website**:
**screenshot**:
**the err.log**:
```

Please wrap the contents of err.log with a code block.
Only paste the ERROR of the date you find the ERROR.

**Comment by lest-day** [comment]
[EN]Reminder: Please use the "New Issue" function, do not comment on this post.

[CN]提醒：请使用”创建新议题“功能，不要于本帖评论反馈。

[ZH]提醒：請使用“創建新議題”功能，不要於本帖評論反饋。
